### ISSUE TITLE
Nothing displayed on the touch bar after clicked search, git and extension button

### ISSUE THREAD

**Issue by Reyshawn** [BlairLeduc/touch-bar-display#5]
VScode version: Version: 1.40.0
System version: macOS Catalina 10.15.1

**Comment by BlairLeduc** [comment]
Thanks, @Reyshawn. Just so I understand, when it disappears is that because something is added to the touch bar when you click those that prevents it from fitting? If you change your control strip on the left to only have two or three items, does the problem go away?

**Comment by eharit** [comment]
I can confirm it, when you're able to type something (editor, search field) the widget is hidden, and the predictive input helper (keyboard) widget shows up. If you turn off the 'Touch Bar typing suggestion' in Settings / Keyboard / Text, the much loved VSCode touch-bar-display's back.
VScode version: Version: 1.40.1
System version: macOS Catalina 10.15.1
